[package]
name = "road_intersection"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3.25"
chrono = "0.4.19"
r = { package = "rand", version = "0.8" }